const Migrations = artifacts.require("Migrations");
/**
 * Standard Migration file generated by truffle suit
 * to deploy migrations.sol file
 * @param {Object} deployer - deployer object to deploy migrations.sol file
 */
module.exports = function (deployer) {
  deployer.deploy(Migrations);
};
