// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

/**
 * This is a standard truffle migration file generated by truffle suit.
 * Migrations, generally speaking, are ways for developers to automate
 * the deployment of data and its supporting structures. They are very
 * useful for managing the deployment of new software versions,
 * and as such aren’t exclusive to blockchain development.
 */
contract Migrations {
    address public owner = msg.sender;
    uint256 public last_completed_migration;

    modifier restricted() {
        require(
            msg.sender == owner,
            "This function is restricted to the contract's owner"
        );
        _;
    }

    function setCompleted(uint256 completed) public restricted {
        last_completed_migration = completed;
    }
}
